### ISSUE TITLE
Upgrade demo C3 feeds consumption using Ogmios

### ISSUE THREAD

**Issue by xxAVOGADROxx** [Charli3-Official/datum-demo-v3#1]
Description
The blockfrost integration fails to retrieve OracleDatum type  correctly, we should use another alternative like maestro or Ogmios

Update Demo on documentation page to include Ogmios because blockfrost integration is failing. This ticket enhances the developer documentation available.

**Comment by c3prime** [comment]
Ogmios alternative implemented to fix bug with demo where it fails because of blockfrost
